########################
# iControlU Plugin.yml #
########################
name: iControlU
version: v1.9.7
main: me.firebreath15.icontrolu.iControlU
author: FireBreath15
depend: [ProtocolLib, LibsDisguises]
commands:
  icu:
    description: Main command for iControlU
    usage: /icu
    permission: icu.use
    permission-message: You don't have permission
permissions:
  icu.use:
    default: true
  icu.control:
    default: op
  icu.stop:
    default: op
  icu.exempt:
    default: false